apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todo-app
  namespace: todo-app
  labels:
    idp-app/type: todo-app
    platform-component/type: app-of-apps
spec:
  destination:
    namespace: todo-app
    server: https://kubernetes.default.svc
  project: default
  source:
    path: helm_chart/todo-app
    repoURL: https://github.com/harishc-biz/todo-app
    targetRevision: HEAD
    helm:
      valueFiles:
        - dev-values.yml
  syncPolicy:
    automated:
      prune: false
      selfHeal: false