trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'todo-app'

steps:

  - task: Docker@2
    inputs:
      containerRegistry: 'acrtododev-acr'
      repository: 'todo-app'
      command: 'buildAndPush'
      Dockerfile: '**/Dockerfile'