trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'todo-app'
  GITHUB_PAT: $(GITHUB_PAT)


stages:
- stage: Docker_Build_and_Push
  displayName: 'Build and Push Docker Image'
  jobs: 
  - job: Build
    displayName: 'Build'
    steps:
    - task: Docker@2
      displayName: 'Build and push an image to container registry'
      inputs:
        containerRegistry: 'acrtododev-acr'
        repository: 'todo-app'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'

- stage: Helm_Chart_Update
  displayName: 'Update Helm Chart'
  jobs:
  - job: Update_values_file
    displayName: 'Update values file'
    steps:
    - checkout: self
      persistCredentials: true
    - task: ShellScript@2
      inputs:
        scriptPath: 'update-values.sh'
        args: '$(Build.BuildId)'