trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'todo-app'

steps:

  - task: Docker@2
    inputs:
      containerRegistry: 'acrtododev-acr'
      repository: 'todo-app'
      command: 'buildAndPush'
      Dockerfile: '**/Dockerfile'

  # - task: CmdLine@2
  #   displayName: 'Update image tag in dev-values.yaml'
  #   inputs:
  #     script: |
  #       chmod +x update-image-tag.sh
  #       ./update-image-tag.sh $(Build.BuildId)

  - task: CmdLine@2
    displayName: 'Update the value yaml with new image tag'
    inputs:
      - script: |
          # Navigate to the Helm chart directory
          cd "$(system.defaultWorkingDirectory)/helm_chart/todo-app"

          # Set the remote URL with the GitHub token
          git remote set-url origin https://$(github-token)@github.com/harishc-biz/todo-app.git

          # Fetch all branches and tags from the remote
          git fetch --all

          # Check out the main branch
          git checkout main

          # Pull the latest changes from the main branch
          git pull origin main

          # Define the path to the values file
          VALUES_FILE="$(system.defaultWorkingDirectory)/helm_chart/todo-app/dev-values.yml"

          # Update the image tag in the values file
          sed -i "s/^\( *tag: *\).*/\1\"$(Build.BuildId)\"/" "$VALUES_FILE"

          # Configure Git
          git config --global user.email "harishdravid9845@gmail.com"
          git config --global user.name "harishc-biz"

          # Add all changes to the staging area
          git add --all

          # Commit the changes
          git commit -m "Latest Values file updated with tag $(Build.BuildId)"

          # Push the changes to the main branch
          git push origin main

          # Print success message
          echo "Values file updated successfully"
        env:
          github-token: $(github-token) # Reference the GitHub token secret
        displayName: 'Update Helm Chart Values'